FROM debian:buster@sha256:a63d0b2ecbd723da612abf0a8bdb594ee78f18f691d7dc652ac305a490c9b71a

SHELL ["/bin/bash", "-c"]

RUN mkdir -p /srv/explorer \
 && apt-get -yqq update \
 && apt-get -yqq upgrade \
 && apt-get -yqq install clang cmake curl git tor

RUN git clone --quiet --depth 1 --single-branch --branch v0.33.11 https://github.com/creationix/nvm.git /root/.nvm \
 && rm -rf /root/.nvm/.git \
 && source /root/.nvm/nvm.sh \
 && nvm install v8.11.4

ENV SHA256SUM_BITCOINCORE=5fcac9416e486d4960e1a946145566350ca670f9aaba99de6542080851122e4c
RUN curl -sL -o bitcoin.tar.gz https://bitcoincore.org/bin/bitcoin-core-0.19.1/bitcoin-0.19.1-x86_64-linux-gnu.tar.gz \
 && echo "${SHA256SUM_BITCOINCORE}  bitcoin.tar.gz" | sha256sum --check \
 && tar xzf bitcoin.tar.gz -C /srv/explorer \
 && ln -s /srv/explorer/bitcoin-0.19.1 /srv/explorer/bitcoin \
 && rm bitcoin.tar.gz

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.41.1 \
 && source /root/.cargo/env \
 && mkdir -p /srv/explorer/electrs{,_liquid} \
 && git clone --no-checkout https://github.com/Groestlcoin/electrs.git \
 && cd electrs \
 && git checkout 49cf7a7dffe8dccb3d4c5cb543aa05878abf086b \
 && cp contrib/popular-scripts.txt /srv/explorer \
 && cargo install --root /srv/explorer/electrs_bitcoin --path . \
 && cd .. \
 && rm -fr /root/.cargo electrs \
 && strip /srv/explorer/electrs_*/bin/electrs


# cleanup
RUN apt-get --auto-remove remove -yqq --purge clang cmake manpages curl git \
 && apt-get clean \
 && apt-get autoclean \
 && rm -rf /usr/share/doc* /usr/share/man /usr/share/postgresql/*/man /var/lib/apt/lists/* /var/cache/* /tmp/* /root/.cache /*.deb /root/.cargo
